// Códigos de error centralizados. Todos deben coincidir con la documentación
// de docs/api.md. El error handler los convierte en { code, message }.

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  CONFLICT: 'CONFLICT',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  CATEGORY_IN_USE: 'CATEGORY_IN_USE',
  SUPPLIER_WHATSAPP_EXISTS: 'SUPPLIER_WHATSAPP_EXISTS',
  INVALID_RELATION: 'INVALID_RELATION',
  FORBIDDEN_DELETE: 'FORBIDDEN_DELETE',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]